### ISSUE TITLE
criar rota /tracking e implementar a tela

### ISSUE THREAD

**Issue by jose15000** [TrackWize/tracking-client#6]
- [x] Criar um Drawer
- [ ] Criar um Step - #8 
- [ ] Criar uma Lista de visualização
- [ ] Criar uma visualização dos dados
